.TH googl "1" "March 2012" "Version 0.1" "User Commands"
.SH NAME
googl \- google url shortener
.SH SYNOPSIS
.B googl
[options] [cmd]
.SH DESCRIPTION
Shorten your URLs from the command line.

For more information about it, you can use its --help flag.
.SH NOTES
All goo.gl URLs and click analytics are public and can be accessed by anyone.
.SH EXAMPLES
\fBgoogl http://github.com\fR
.br
\fBgoogl search git\fR
.br
\fBgoogl open git\fR
.br
\fBgoogl ls\fR
.SH AUTHOR
Written by Rainer Borene.
.SH "REPORTING BUGS"
Please file bugs at https://github.com/rainerborene/googl/issues/
.SH SEE ALSO
.BR curl(1),
.BR grep(1),
.BR pbcopy(1)
