.TH Googl "1" "March 2012" "googl" "User Commands"

.SH NAME
googl \- google url shortener

.SH SYNOPSIS
googl [url]

.SH AVAILABILITY
bash, zsh

.SH DESCRIPTION
Shorten your URLs from the command line.

.SH NOTES
All goo.gl URLs and click analytics are public and can be accessed by anyone.

.SH EXAMPLES
\fBgoogl http://github.com\fR

.SH SEE ALSO
curl(1), grep(2), pbcopy(3)

.P
Please file bugs at https://github.com/rainerborene/googl/
